name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Create and populate .env file
      run: |
        touch .env
        echo PAYSTACK_SECRET_KEY=${{ vars.PAYSTACK_SECRET_KEY }} >> .env
        echo PAYSTACK_PUBLIC_KEY=${{ vars.PAYSTACK_PUBLIC_KEY }} >> .env
        echo DB_USER=${{ vars.DB_USER }} >> .env
        echo DB_PASSWORD=${{ vars.DB_PASSWORD }} >> .env
        echo DB_HOST=${{ vars.DB_HOST }} >> .env
        echo DB_NAME=${{ vars.DB_NAME }} >> .env

    - run: npm install
    - run: npm run build --if-present
    - run: npm run eslint:fix
    - run: npm test
