name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  PAYSTACK_SECRET_KEY: ${{ vars.PAYSTACK_SECRET_KEY }}
  PAYSTACK_PUBLIC_KEY: ${{ vars.PAYSTACK_PUBLIC_KEY }}
  DB_USER: ${{ vars.DB_USER }}
  DB_PASSWORD: ${{ vars.DB_PASSWORD }}
  DB_HOST: ${{ vars.DB_HOST }}
  DB_NAME: ${{ vars.DB_NAME }}

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm install
    - run: npm run build --if-present
    - run: npm run eslint:fix
    - run: npm test
